name: Auto Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            # Masuk ke direktori proyek
            cd /www/wwwroot/mtsnpadangpanjang.sch.id